<?php

/* 
 * Copyright 2014 TILKEE.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$dictionary['TILKEE_TILKS'] = array(
'table'=>'tilkee_tilks',
'audited'=>true,
        'duplicate_merge'=>true,
        'fields'=>array (
            'tilkee_contact_id' => 
            array (
              'required' => false,
              'name' => 'tilkee_contact_id',
              'vname' => 'LBL_TILKEE_CONTACT_ID',
              'type' => 'int',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => '255',
              'size' => '20',
              'enable_range_search' => false,
              'disable_num_format' => '',
              'min' => false,
              'max' => false,
            ),
            'tilk_url' => 
            array (
              'required' => false,
              'name' => 'tilk_url',
              'vname' => 'LBL_TILK_URL',
              'type' => 'url',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => '255',
              'size' => '20',
              'dbType' => 'varchar',
              'gen' => '',
              'link_target' => '_blank',
            ),
            'total_time' => 
            array (
              'required' => false,
              'name' => 'total_time',
              'vname' => 'LBL_TOTAL_TIME',
              'type' => 'varchar',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => '255',
              'size' => '20',
            ),
            'total_connexion' => 
            array (
              'required' => false,
              'name' => 'total_connexion',
              'vname' => 'LBL_TOTAL_CONNEXION',
              'type' => 'int',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => '255',
              'size' => '20',
              'enable_range_search' => false,
              'disable_num_format' => '',
              'min' => false,
              'max' => false,
            ),
            'contact_email' => 
            array (
              'required' => false,
              'name' => 'contact_email',
              'vname' => 'LBL_CONTACT_EMAIL',
              'type' => 'varchar',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => '255',
              'size' => '20',
            ),
            'last_sign_in_at' => 
            array (
              'required' => false,
              'name' => 'last_sign_in_at',
              'vname' => 'LBL_LAST_SIGN_IN_AT',
              'type' => 'datetime',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'size' => '20',
              'enable_range_search' => false,
              'dbType' => 'datetime',
            ),
            'created_at' => 
            array (
              'required' => false,
              'name' => 'created_at',
              'vname' => 'LBL_CREATED_AT',
              'type' => 'datetime',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'size' => '20',
              'enable_range_search' => false,
              'dbType' => 'datetime',
            ),
            'won' => 
            array (
              'required' => false,
              'name' => 'won',
              'vname' => 'LBL_WON',
              'type' => 'enum',
              'massupdate' => 0,
              'no_default' => false,
              'default' => '',
              'comments' => '',
              'help' => '',
              'importable' => 'true',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => 100,
              'size' => '20',
              'options' => 'won_archived_list',
              'studio' => 'visible',
              'dependency' => false,
            ),
            'archived' => 
            array (
              'required' => false,
              'name' => 'archived',
              'vname' => 'LBL_ARCHIVED',
              'type' => 'enum',
              'massupdate' => 0,
              'no_default' => false,
              'default' => '',
              'comments' => '',
              'help' => '',
              'importable' => 'true',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => 100,
              'size' => '20',
              'options' => 'won_archived_list',
              'studio' => 'visible',
              'dependency' => false,
            ),
            'archived_at' => 
            array (
              'required' => false,
              'name' => 'archived_at',
              'vname' => 'LBL_ARCHIVED_AT',
              'type' => 'datetime',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'size' => '20',
              'enable_range_search' => false,
              'dbType' => 'datetime',
            ),
            'tilkee_id' => 
            array (
              'required' => false,
              'name' => 'tilkee_id',
              'vname' => 'LBL_TILKEEE_ID',
              'type' => 'int',
              'massupdate' => 0,
              'no_default' => false,
              'comments' => '',
              'help' => '',
              'importable' => 'false',
              'duplicate_merge' => 'disabled',
              'duplicate_merge_dom_value' => '0',
              'audited' => false,
              'reportable' => true,
              'unified_search' => false,
              'merge_filter' => 'disabled',
              'len' => '255',
              'size' => '20',
              'enable_range_search' => false,
              'disable_num_format' => '',
              'min' => false,
              'max' => false,
            ),
        ),
	'relationships'=>array (),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('TILKEE_TILKS','TILKEE_TILKS', array('basic','assignable'));