<?php

/* 
 * Copyright 2014 TILKEE.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$dictionary['TILKEE_PROJECTS'] = array(
    'table'=>'tilkee_projects',
    'audited'=>true,
            'duplicate_merge'=>true,
            'fields'=>array (
    'type' => 
        array (
          'required' => false,
          'name' => 'type',
          'vname' => 'LBL_TYPE',
          'type' => 'enum',
          'massupdate' => 0,
          'default' => 'proposal',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 100,
          'size' => '20',
          'options' => 'type_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'leader' => 
        array (
          'required' => false,
          'name' => 'leader',
          'vname' => 'LBL_LEADER',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),
        'leader_id' => 
        array (
          'required' => false,
          'name' => 'leader_id',
          'vname' => 'LBL_LEADER_ID',
          'type' => 'int',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
        ),
        'status' => 
        array (
          'required' => false,
          'name' => 'status',
          'vname' => 'LBL_STATUS',
          'type' => 'enum',
          'massupdate' => 0,
          'default' => 'reviewing',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 100,
          'size' => '20',
          'options' => 'status_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'won' => 
        array (
          'required' => false,
          'name' => 'won',
          'vname' => 'LBL_WON',
          'type' => 'enum',
          'massupdate' => 0,
          'default' => '',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 100,
          'size' => '20',
          'options' => 'won_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'tilks_count' => 
        array (
          'required' => false,
          'name' => 'tilks_count',
          'vname' => 'LBL_TILKS_COUNT',
          'type' => 'int',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
        ),
        'active_tilk' => 
        array (
          'required' => false,
          'name' => 'active_tilk',
          'vname' => 'LBL_ACTIVE_TILK',
          'type' => 'int',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
        ),
        'total_connexions' => 
        array (
          'required' => false,
          'name' => 'total_connexions',
          'vname' => 'LBL_TOTAL_CONNEXIONS',
          'type' => 'int',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
        ),
        'total_time' => 
        array (
          'required' => false,
          'name' => 'total_time',
          'vname' => 'LBL_TOTAL_TIME',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),
        'created_at' => 
        array (
          'required' => false,
          'name' => 'created_at',
          'vname' => 'LBL_CREATED_AT',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
        'updated_at' => 
        array (
          'required' => false,
          'name' => 'updated_at',
          'vname' => 'LBL_UPDATED_AT',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
        'activated_at' => 
        array (
          'required' => false,
          'name' => 'activated_at',
          'vname' => 'LBL_ACTIVATED_AT',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
        'last_sign_in_at' => 
        array (
          'required' => false,
          'name' => 'last_sign_in_at',
          'vname' => 'LBL_LAST_SIGN_IN_AT',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
        'archived_at' => 
        array (
          'required' => false,
          'name' => 'archived_at',
          'vname' => 'LBL_ARCHIVED_AT',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
        'deleted_at' => 
        array (
          'required' => false,
          'name' => 'deleted_at',
          'vname' => 'LBL_DELETED_AT',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),                
        'visible_since' => 
        array (
          'required' => false,
          'name' => 'visible_since',
          'vname' => 'LBL_VISIBLE_SINCE',
          'type' => 'datetime',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => false,
          'dbType' => 'datetime',
        ),
        'url' => 
        array (
          'required' => false,
          'name' => 'url',
          'vname' => 'LBL_URL',
          'type' => 'url',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'dbType' => 'varchar',
          'gen' => '',
          'link_target' => '_blank',
        ),
        'preview_url' => 
        array (
          'required' => false,
          'name' => 'preview_url',
          'vname' => 'LBL_PREVIEW_URL',
          'type' => 'url',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'dbType' => 'varchar',
          'gen' => '',
          'link_target' => '_blank',
        ),
        'edit_url' => 
        array (
          'required' => false,
          'name' => 'edit_url',
          'vname' => 'LBL_EDIT_URL',
          'type' => 'url',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'dbType' => 'varchar',
          'gen' => '',
          'link_target' => '_blank',
        ),
        'stat_url' => 
        array (
          'required' => false,
          'name' => 'stat_url',
          'vname' => 'LBL_STAT_URL',
          'type' => 'url',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'dbType' => 'varchar',
          'gen' => '',
          'link_target' => '_blank',
        ),
        'stat_iframe' => 
        array (
          'required' => false,
          'name' => 'stat_iframe',
          'vname' => 'LBL_STAT_IFRAME',
          'type' => 'iframe',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'dbType' => 'varchar',
          'gen' => '',
          'link_target' => '200',
          'height' => '200',
        ),
        'tilkee_id' => 
        array (
          'required' => false,
          'name' => 'tilkee_id',
          'vname' => 'LBL_TILKEE_ID',
          'type' => 'int',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'false',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
        ),
    ),
    'relationships'=>array (
    ),
    'optimistic_locking'=>true,
    'unified_search'=>true,
);

if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}

VardefManager::createVardef('TILKEE_PROJECTS','TILKEE_PROJECTS', array('basic','assignable'));